# Generated by Django 5.2.1 on 2025-05-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='cantidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='idProducto',
            field=models.CharField(max_length=50),
        ),
    ]
