# Generated by Django 5.2.1 on 2025-05-29 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_alter_ingreso_cantidad_alter_ingreso_idproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
