# Generated by Django 5.2.1 on 2025-06-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='CantidadSolicitada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orden',
            name='PrecioUnidadSolicitada',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orden',
            name='PresentacionSolicitada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orden',
            name='idOrdenCompra',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='idProducto',
            field=models.IntegerField(),
        ),
    ]
