# Generated by Django 5.2.1 on 2025-06-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0002_alter_orden_cantidadsolicitada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='CantidadSolicitada',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='PrecioUnidadSolicitada',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='PresentacionSolicitada',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='idProducto',
        ),
    ]
