# Generated by Django 5.2.1 on 2025-06-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0003_remove_orden_cantidadsolicitada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='idOrdenCompra',
        ),
        migrations.AddField(
            model_name='orden',
            name='nombre_orden',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
