# Generated by Django 5.2.1 on 2025-07-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_compra', '0004_remove_orden_idordencompra_orden_nombre_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='nombre_orden',
        ),
        migrations.AddField(
            model_name='orden',
            name='observacion_orden',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
