# Generated by Django 5.2.1 on 2025-06-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='CantidadProductoblue',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idProducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='CantidadProducto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='producto',
            name='PresentacionProducto',
            field=models.IntegerField(),
        ),
    ]
